name: Java CI Pipeline

on:
  push:
    branches: [ main, phase-3 ]
  pull_request:
    branches: [ main, phase-3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo Kodlarini Cek
      uses: actions/checkout@v4

    - name: Java JDK 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Kodu Derle (Compile)
      run: |
        mkdir -p bin
        javac -d bin src/OyunMotoru.java

    - name: Projeyi Test Et (Run)
      run: java -cp bin OyunMotoru